# Generated by Django 4.0.3 on 2022-04-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
